db:
  build: db
  volumes:
    - ./volumes/db/var/lib/mysql:/var/lib/mysql
    - /etc/localtime:/etc/localtime:ro
app:
  build: app
  links:
    - db:db
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
web:
  build: web
  ports:
    - "443:443"
    - "80:80"
  links:
    - app:platform
  volumes:
    - /etc/localtime:/etc/localtime:ro
